language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

after_success:
  - travis_retry php vendor/bin/coveralls -v