language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

addons:
  code_climate:
    repo_token: f88bd1bbb15936c8e8a5e2d93031b09d20d84b15abc097ae8fba858964ed8509

after_success:
  - vendor/bin/test-reporter
