language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

addons:
  code_climate:
    repo_token: 433b6c8f7f24b291b86a6448711a252f894668fbfb120411dbca66d37c5874e4

after_success:
  - vendor/bin/test-reporter